
lint.ignore = [
    "docstring-in-stub",        # Literally against the purpose of this plugin
    "line-contains-todo",
    "missing-copyright-notice", # Ignore licence header
    "missing-todo-author",
    "missing-todo-link",
    "superfluous-else-return",  # I don't like this rule
]
lint.select = ["ALL"]
preview = true
[format]
    docstring-code-format = true
    preview               = true
[lint.pydocstyle]
    convention = "google"
[lint.per-file-ignores]
    "src/pql/sql/_code_gen/*.py" = [
        "any-type",
        "boolean-default-value-positional-argument",
        "boolean-type-hint-positional-argument",
        "builtin-argument-shadowing",
        "eq-without-hash",
        "too-many-arguments",
    ]
    "t.py" = [
        "missing-return-type-undocumented-public-function",
        "undocumented-public-class",
        "undocumented-public-function",
        "undocumented-public-module",
    ]
    "tests/*" = [
        "assert",
        "boolean-type-hint-positional-argument",
        "call-datetime-without-tzinfo",
        "undocumented-public-class",
        "undocumented-public-function",
        "undocumented-public-method",
        "undocumented-public-module",
        "undocumented-public-package",
    ]
[lint.isort]
    combine-as-imports = true
