
lint.ignore = [
    "missing-copyright-notice", # Ignore licence header
    "docstring-in-stub", # Literally against the purpose of this plugin
]
lint.select = ["ALL"]
preview = true
[format]
    docstring-code-format = true
    preview               = true
[lint.pydocstyle]
    convention = "google"
[lint.per-file-ignores]
    "src/pql/sql/_code_gen/*.py" = [
        "builtin-argument-shadowing",
        "any-type",
        "boolean-type-hint-positional-argument",
        "boolean-default-value-positional-argument",
        "too-many-arguments",
        "eq-without-hash",
    ]
    "t.py" = ["missing-return-type-undocumented-public-function", "undocumented-public-module", "undocumented-public-class", "undocumented-public-function"]
    "tests/*" = [
        "undocumented-public-module",
        "undocumented-public-class",
        "undocumented-public-method",
        "undocumented-public-function",
        "undocumented-public-package",
        "call-datetime-without-tzinfo",
        "boolean-type-hint-positional-argument",
        "assert",
    ]
[lint.isort]
    combine-as-imports = true
